//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FlickrResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FlickrResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.FlickrResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current topic's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr Slide Show.
        /// </summary>
        internal static string FeatureName {
            get {
                return ResourceManager.GetString("FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr API Key.
        /// </summary>
        internal static string FlickrApiKey {
            get {
                return ResourceManager.GetString("FlickrApiKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must enter your Flickr Username and API Key..
        /// </summary>
        internal static string FlickrNotConfiguredWarning {
            get {
                return ResourceManager.GetString("FlickrNotConfiguredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flickr User Name.
        /// </summary>
        internal static string FlickrUserName {
            get {
                return ResourceManager.GetString("FlickrUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Height.
        /// </summary>
        internal static string SlideShowHeight {
            get {
                return ResourceManager.GetString("SlideShowHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Theme.
        /// </summary>
        internal static string SlideShowTheme {
            get {
                return ResourceManager.GetString("SlideShowTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slide Show Width.
        /// </summary>
        internal static string SlideShowWidth {
            get {
                return ResourceManager.GetString("SlideShowWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make Slide Show Windowless?.
        /// </summary>
        internal static string SlideShowWindowlessMode {
            get {
                return ResourceManager.GetString("SlideShowWindowlessMode", resourceCulture);
            }
        }
    }
}
