//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GroupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.GroupResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current topic's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe of user from group notification completed..
        /// </summary>
        internal static string AdminUnsubscribeUserComplete {
            get {
                return ResourceManager.GetString("AdminUnsubscribeUserComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow Anonymous Posts?.
        /// </summary>
        internal static string AllowAnonymousPostsLabel {
            get {
                return ResourceManager.GetString("AllowAnonymousPostsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Wait....
        /// </summary>
        internal static string ButtonDisabledPleaseWait {
            get {
                return ResourceManager.GetString("ButtonDisabledPleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to First Page.
        /// </summary>
        internal static string CutePagerBackToFirstClause {
            get {
                return ResourceManager.GetString("CutePagerBackToFirstClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Page.
        /// </summary>
        internal static string CutePagerBackToPageClause {
            get {
                return ResourceManager.GetString("CutePagerBackToPageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to Last Page.
        /// </summary>
        internal static string CutePagerGoToLastClause {
            get {
                return ResourceManager.GetString("CutePagerGoToLastClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigate to Page.
        /// </summary>
        internal static string CutePagerNavigateToPageText {
            get {
                return ResourceManager.GetString("CutePagerNavigateToPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next to Page.
        /// </summary>
        internal static string CutePagerNextToPageClause {
            get {
                return ResourceManager.GetString("CutePagerNextToPageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string CutePagerOfClause {
            get {
                return ResourceManager.GetString("CutePagerOfClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string CutePagerPageClause {
            get {
                return ResourceManager.GetString("CutePagerPageClause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string EditImageAltText {
            get {
                return ResourceManager.GetString("EditImageAltText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailLabel {
            get {
                return ResourceManager.GetString("EmailLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this post?.
        /// </summary>
        internal static string GroupDeletePostWarning {
            get {
                return ResourceManager.GetString("GroupDeletePostWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this topic?.
        /// </summary>
        internal static string GroupDeleteTopicWarning {
            get {
                return ResourceManager.GetString("GroupDeleteTopicWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GroupEditCancelButton {
            get {
                return ResourceManager.GetString("GroupEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string GroupEditCancelButtonAccessKey {
            get {
                return ResourceManager.GetString("GroupEditCancelButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Group.
        /// </summary>
        internal static string GroupEditCreateButton {
            get {
                return ResourceManager.GetString("GroupEditCreateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By:.
        /// </summary>
        internal static string GroupEditCreatedByLabel {
            get {
                return ResourceManager.GetString("GroupEditCreatedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string GroupEditCreatedDateLabel {
            get {
                return ResourceManager.GetString("GroupEditCreatedDateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this item.
        /// </summary>
        internal static string GroupEditDeleteButton {
            get {
                return ResourceManager.GetString("GroupEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string GroupEditDeleteButtonAccessKey {
            get {
                return ResourceManager.GetString("GroupEditDeleteButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string GroupEditDescriptionLabel {
            get {
                return ResourceManager.GetString("GroupEditDescriptionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Group.
        /// </summary>
        internal static string GroupEditGroupLabel {
            get {
                return ResourceManager.GetString("GroupEditGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active?.
        /// </summary>
        internal static string GroupEditIsActiveLabel {
            get {
                return ResourceManager.GetString("GroupEditIsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Moderated?.
        /// </summary>
        internal static string GroupEditIsModeratedLabel {
            get {
                return ResourceManager.GetString("GroupEditIsModeratedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Group.
        /// </summary>
        internal static string GroupEditLabel {
            get {
                return ResourceManager.GetString("GroupEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Group.
        /// </summary>
        internal static string GroupEditNewGroupButton {
            get {
                return ResourceManager.GetString("GroupEditNewGroupButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Post.
        /// </summary>
        internal static string GroupEditPostLink {
            get {
                return ResourceManager.GetString("GroupEditPostLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posts Per Page:.
        /// </summary>
        internal static string GroupEditPostsPerPageLabel {
            get {
                return ResourceManager.GetString("GroupEditPostsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order:.
        /// </summary>
        internal static string GroupEditSortOrderLabel {
            get {
                return ResourceManager.GetString("GroupEditSortOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You Must Enter a Subject.
        /// </summary>
        internal static string GroupEditSubjectRequiredHelp {
            get {
                return ResourceManager.GetString("GroupEditSubjectRequiredHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        internal static string GroupEditTitleLabel {
            get {
                return ResourceManager.GetString("GroupEditTitleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics Per Page:.
        /// </summary>
        internal static string GroupEditTopicsPerPageLabel {
            get {
                return ResourceManager.GetString("GroupEditTopicsPerPageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GroupEditUpdateButton {
            get {
                return ResourceManager.GetString("GroupEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GroupEditUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("GroupEditUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable SPAM Blocking?.
        /// </summary>
        internal static string GroupEnableAntiSpamSetting {
            get {
                return ResourceManager.GetString("GroupEnableAntiSpamSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSS At Group Level?.
        /// </summary>
        internal static string GroupEnableRSSAtGroupLevel {
            get {
                return ResourceManager.GetString("GroupEnableRSSAtGroupLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSS At Module Level?.
        /// </summary>
        internal static string GroupEnableRSSAtModuleLevel {
            get {
                return ResourceManager.GetString("GroupEnableRSSAtModuleLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable RSS At Topic Level?.
        /// </summary>
        internal static string GroupEnableRSSAtTopicLevel {
            get {
                return ResourceManager.GetString("GroupEnableRSSAtTopicLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupLabel {
            get {
                return ResourceManager.GetString("GroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A discussion group for {0}.
        /// </summary>
        internal static string GroupMetaDescriptionFormat {
            get {
                return ResourceManager.GetString("GroupMetaDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Email Subscriptions.
        /// </summary>
        internal static string GroupModuleEditSubscriptionsLabel {
            get {
                return ResourceManager.GetString("GroupModuleEditSubscriptionsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupModuleGroupLabel {
            get {
                return ResourceManager.GetString("GroupModuleGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Posts.
        /// </summary>
        internal static string GroupModulePostCountLabel {
            get {
                return ResourceManager.GetString("GroupModulePostCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string GroupModulePostLastPostLabel {
            get {
                return ResourceManager.GetString("GroupModulePostLastPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe?.
        /// </summary>
        internal static string GroupModuleSubscribedLabel {
            get {
                return ResourceManager.GetString("GroupModuleSubscribedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Topics.
        /// </summary>
        internal static string GroupModuleTopicCountLabel {
            get {
                return ResourceManager.GetString("GroupModuleTopicCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Posts.
        /// </summary>
        internal static string GroupMyPostsLink {
            get {
                return ResourceManager.GetString("GroupMyPostsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GroupPostEditCancelButton {
            get {
                return ResourceManager.GetString("GroupPostEditCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string GroupPostEditDeleteButton {
            get {
                return ResourceManager.GetString("GroupPostEditDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        internal static string GroupPostEditMessageLabel {
            get {
                return ResourceManager.GetString("GroupPostEditMessageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to replies on this topic?.
        /// </summary>
        internal static string GroupPostEditNotifyLabel {
            get {
                return ResourceManager.GetString("GroupPostEditNotifyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string GroupPostEditSubjectLabel {
            get {
                return ResourceManager.GetString("GroupPostEditSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post.
        /// </summary>
        internal static string GroupPostEditUpdateButton {
            get {
                return ResourceManager.GetString("GroupPostEditUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string GroupPostEditUpdateButtonAccessKey {
            get {
                return ResourceManager.GetString("GroupPostEditUpdateButtonAccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GroupsFeatureName {
            get {
                return ResourceManager.GetString("GroupsFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must sign in to post in the groups..
        /// </summary>
        internal static string GroupsLoginRequiredLink {
            get {
                return ResourceManager.GetString("GroupsLoginRequiredLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        internal static string GroupsSearchName {
            get {
                return ResourceManager.GetString("GroupsSearchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tables contains a list of Groups..
        /// </summary>
        internal static string GroupsTableSummary {
            get {
                return ResourceManager.GetString("GroupsTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Subscriptions.
        /// </summary>
        internal static string GroupSubscriptions {
            get {
                return ResourceManager.GetString("GroupSubscriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string GroupTopicCancelButton {
            get {
                return ResourceManager.GetString("GroupTopicCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string GroupTopicDeleteButton {
            get {
                return ResourceManager.GetString("GroupTopicDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        internal static string GroupTopicEditGroupLabel {
            get {
                return ResourceManager.GetString("GroupTopicEditGroupLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Topic.
        /// </summary>
        internal static string GroupTopicEditLabel {
            get {
                return ResourceManager.GetString("GroupTopicEditLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Order.
        /// </summary>
        internal static string GroupTopicEditSortOrderLabel {
            get {
                return ResourceManager.GetString("GroupTopicEditSortOrderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string GroupTopicEditSubjectLabel {
            get {
                return ResourceManager.GetString("GroupTopicEditSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Topic - {0}.
        /// </summary>
        internal static string GroupTopicMetaDescriptionFormat {
            get {
                return ResourceManager.GetString("GroupTopicMetaDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe completed!  You should not receive any more notifications for messages in the requested topic..
        /// </summary>
        internal static string GroupTopicUnsubscribeCompleted {
            get {
                return ResourceManager.GetString("GroupTopicUnsubscribeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe FAILED!  An error occurred when attempting to stop notifications for a topic.  Please contact the site administrator..
        /// </summary>
        internal static string GroupTopicUnsubscribeFailed {
            get {
                return ResourceManager.GetString("GroupTopicUnsubscribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string GroupTopicUpdateButton {
            get {
                return ResourceManager.GetString("GroupTopicUpdateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        internal static string GroupTopicViewAuthorLabel {
            get {
                return ResourceManager.GetString("GroupTopicViewAuthorLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages:.
        /// </summary>
        internal static string GroupTopicViewPagesLabel {
            get {
                return ResourceManager.GetString("GroupTopicViewPagesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reply.
        /// </summary>
        internal static string GroupTopicViewReplyLabel {
            get {
                return ResourceManager.GetString("GroupTopicViewReplyLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe completed!  You should not receive any more notifications for new topics in the requested group..
        /// </summary>
        internal static string GroupUnsubscribeCompleted {
            get {
                return ResourceManager.GetString("GroupUnsubscribeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe FAILED!  An error occurred when attempting to stop notifications for new topics in a group.  Please contact the site administrator..
        /// </summary>
        internal static string GroupUnsubscribeFailed {
            get {
                return ResourceManager.GetString("GroupUnsubscribeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Posts.
        /// </summary>
        internal static string GroupUserPostsLink {
            get {
                return ResourceManager.GetString("GroupUserPostsLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} participated in these discussions..
        /// </summary>
        internal static string GroupUserTopicHeading {
            get {
                return ResourceManager.GetString("GroupUserTopicHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new topic.
        /// </summary>
        internal static string GroupViewNewTopicLabel {
            get {
                return ResourceManager.GetString("GroupViewNewTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Post.
        /// </summary>
        internal static string GroupViewPostLastPostLabel {
            get {
                return ResourceManager.GetString("GroupViewPostLastPostLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Replies.
        /// </summary>
        internal static string GroupViewReplyCountLabel {
            get {
                return ResourceManager.GetString("GroupViewReplyCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started by.
        /// </summary>
        internal static string GroupViewStartedByLabel {
            get {
                return ResourceManager.GetString("GroupViewStartedByLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        internal static string GroupViewSubjectLabel {
            get {
                return ResourceManager.GetString("GroupViewSubjectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This table contains a list of Group Topics..
        /// </summary>
        internal static string GroupViewTableSummary {
            get {
                return ResourceManager.GetString("GroupViewTableSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Topics.
        /// </summary>
        internal static string GroupViewTopicCountLabel {
            get {
                return ResourceManager.GetString("GroupViewTopicCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Views.
        /// </summary>
        internal static string GroupViewViewCountLabel {
            get {
                return ResourceManager.GetString("GroupViewViewCountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include Post Body in Notification Email?.
        /// </summary>
        internal static string IncludePostBodyInNotificationEmail {
            get {
                return ResourceManager.GetString("IncludePostBodyInNotificationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        internal static string LoginNameLabel {
            get {
                return ResourceManager.GetString("LoginNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Topic.
        /// </summary>
        internal static string NewTopicLabel {
            get {
                return ResourceManager.GetString("NewTopicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include items up to this many days old in outbound feed..
        /// </summary>
        internal static string RSSFeedMaxDaysOldSetting {
            get {
                return ResourceManager.GetString("RSSFeedMaxDaysOldSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of items to include in outbound feed..
        /// </summary>
        internal static string RSSFeedMaxPostsSetting {
            get {
                return ResourceManager.GetString("RSSFeedMaxPostsSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter some text to search for..
        /// </summary>
        internal static string SearchTermRequiredWarning {
            get {
                return ResourceManager.GetString("SearchTermRequiredWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Subscriber Count?.
        /// </summary>
        internal static string ShowSubscriberCount {
            get {
                return ResourceManager.GetString("ShowSubscriberCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        internal static string SubscribeLink {
            get {
                return ResourceManager.GetString("SubscribeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to notifications for this group.
        /// </summary>
        internal static string SubscribeLongLink {
            get {
                return ResourceManager.GetString("SubscribeLongLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Subscribers.
        /// </summary>
        internal static string SubscriberCountFormat {
            get {
                return ResourceManager.GetString("SubscriberCountFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to all posts in this group?.
        /// </summary>
        internal static string SubscribeToAllOfThisGroup {
            get {
                return ResourceManager.GetString("SubscribeToAllOfThisGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnsubscribeButton {
            get {
                return ResourceManager.GetString("UnsubscribeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribe.
        /// </summary>
        internal static string UnSubscribeLink {
            get {
                return ResourceManager.GetString("UnSubscribeLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string UserNameLabel {
            get {
                return ResourceManager.GetString("UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        internal static string UserSalesLabel {
            get {
                return ResourceManager.GetString("UserSalesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site member {0} participated in these group conversations..
        /// </summary>
        internal static string UserTopicMetaFormat {
            get {
                return ResourceManager.GetString("UserTopicMetaFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Topics for {0}.
        /// </summary>
        internal static string UserTopicTitleFormat {
            get {
                return ResourceManager.GetString("UserTopicTitleFormat", resourceCulture);
            }
        }
    }
}
